# Generated by Django 4.0 on 2022-01-19 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_doctor', '0002_alter_viddoc_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_doctor.doctor'),
        ),
    ]
