# Generated by Django 3.1.7 on 2022-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logd',
            name='veri',
            field=models.CharField(default='No', max_length=50),
        ),
    ]
