# Generated by Django 4.0 on 2022-01-20 03:37

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=400)),
                ('measures', models.CharField(max_length=1000)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
