# Generated by Django 3.1.7 on 2022-01-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
