# Generated by Django 3.1.7 on 2022-01-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplabtest', '0002_auto_20220118_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='shoplabtest/images'),
        ),
    ]
