# Generated by Django 3.1.7 on 2022-01-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplabtest', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
