# Generated by Django 3.1.7 on 2022-01-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplabtest', '0004_remove_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
