# Generated by Django 3.1.7 on 2022-01-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplabtest', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='shoplabtest/images'),
        ),
    ]
