# Generated by Django 3.1.7 on 2022-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplabtest', '0009_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
